### ISSUE TITLE
IOS error

### ISSUE THREAD

**Issue by hernasenjohn** [tschoffelen/php-pkpass#101]
Good. When generating a pass with the app on android it works perfectly for me both when I download it and when I open it. But in ios it fails me, in the download safari it gives me an error and if I do it in android and I send it by email to ios it doesn't open either. but in android it is perfect, I don't know why.

http://pk-pass.herokuapp.com/rentingpass/

**Comment by tschoffelen** [comment]
Console on Mac gives me the following error when opening a pass created via your web app:

![image](https://user-images.githubusercontent.com/666220/84668641-c9a17180-af1b-11ea-9973-037037c96c5a.png)


Have a look at the README for instructions on how to debug issues on Mac.

**Comment by hernasenjohn** [comment]
Repair the error but on iphone it still doesn't work well.

**Comment by tschoffelen** [comment]
There might be another error in your JSON, or there might be something wrong with your signing certificate. The Console app on your Mac will show you the exact error message.

**Comment by hernasenjohn** [comment]
Tengo una duda. Es necesario sustituir el archivo .pem?

**Comment by hernasenjohn** [comment]
I have a doubt. Do I need to replace the .pem file?

**Comment by tschoffelen** [comment]
What error is the console showing you?

**Comment by Waruo** [comment]
Perhaps p12 certificate has not expired?

**Comment by hernasenjohn** [comment]
Everything is correct. The problem was in the pass, which was wrongly created by those who keep the apple account and named it. Now it works perfect. Thank you very much and sorry for the inconvenience.

**Comment by tschoffelen** [comment]
Great to hear! Thanks for using this library 👍
