### ISSUE TITLE
Unable to open or port .pkpass file

### ISSUE THREAD

**Issue by devndumngalon** [tschoffelen/php-pkpass#151]
### Expected Behavior
Add .pkpass to the Apple Wallet

### Actual Behavior
Opens a blank screen with file size and filename

![462556932_1956007844873558_4182366785786091593_n](https://github.com/user-attachments/assets/2c9e9659-4569-489b-b686-6eeb911c20f1)

Wanted to ask if someone is experiencing the same thing trying to open the .pkpass file on their iphone in the hopes of adding it to the Apple Wallet. Are can you point me to what is the reason I'm unable to open the .pkpass.

I tried debugging it by connecting my phone to my macbook but cannot seem to fiend "Pass Viewer" when clicking the file.

Thank you!

**Comment by Annawoody** [comment]
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID APP07638
Please see the link below to our dedicated support line:
[Apple wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@devndumngalon

**Comment by Annawoody** [comment]
The support team website 
@devndumngalon

**Comment by devndumngalon** [comment]
Done

**Comment by Annawoody** [comment]
Okay they should be able to figure something out 
@devndumngalon

**Comment by tschoffelen** [comment]
@Annawoody how are you related to this package?

**Comment by devndumngalon** [comment]
its a scam @tschoffelen, unable to report his account

**Comment by tschoffelen** [comment]
So sorry about that @devndumngalon! I've reported them.

In terms of being able to debug the pass - it seems like perhaps somehow the content-type of the pass is not being set correctly by your webserver. Have a look at this Stackoverflow question here:

https://stackoverflow.com/questions/15383552/how-to-set-mime-type-of-application-vnd-apple-pkpass-in-order-to-share-pass-by-l

**Comment by devndumngalon** [comment]
Thanks @tschoffelen, appreciate it! 

I will try your suggestion, thanks!

**Comment by devndumngalon** [comment]
Hi @tschoffelen, I was able to find the cause of my error. So it was related to an invalid data, I was passing an integer serialNumber instead of a string.

Thanks again for the help!
