### ISSUE TITLE
Broken with iOS7?

### ISSUE THREAD

**Issue by jarretth** [tschoffelen/PHP-PKPass#41]
I notice that http://apps.tomttb.com/pkpass/full_sample does not work on iOS 7. The downloaded pass will load into the iOS simulator, but in Safari I'm getting 
"Download Failed - Safari cannot download this file.", and in mobile Chrome I'm getting "Sorry, this pass cannot be added to Passbook at this time".

**Comment by welsby** [comment]
Same issue here, but nothing is showing when I tail system.log after dragging a pass file into the simulator.
Any suggestions?

**Comment by jarretth** [comment]
Two suggestions:
1. Make sure you're using a valid certificate. The one in the sample, if it's still generating invalid passes, is likely expired
2. As suggested, the iOS Simulator's console output(Debug > Open System Log / cmd+/) should give you all you need to know about pass formatting issues. The most common issue I run into is my application putting null in the json where a value is required(ie, the "value" index of a field dictionary).

The sample's error output is:
```
Jul 27 17:03:26 j.local MobileSafari[96561]:  SecTrustEvaluate  [leaf ValidLeaf]
Jul 27 17:03:26 j.local MobileSafari[96561]: Invalid data error reading pass pass.nl.mijnbc.test/123456. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.
Jul 27 17:03:26 j.local MobileSafari[96561]: PassBook Pass download failed: The pass cannot be read because it isn’t valid.
```

Note that the OSX passbook loader is much more lenient than iOS's, so using the simulator is important. 

As I can verify that the library is still working as expected for all current versions of iOS, I am closing this issue.
