### ISSUE TITLE
after generating pass.pkpass file its not working or not opening in any device

### ISSUE THREAD

**Issue by mastermind4242** [tschoffelen/PHP-PKPass#42]
In i os7 its not opening please help what to do if i want to use this in i os7

Hi,
I am trying to use this PKPASS.php class for generating .pkpass files.

But after generating pass.pkpass file when we are opening this file in apple passbook app OR in mac system it is not getting open.
other .pkpass files are working fine.

In i os7 its not opening please help what to do if i want to use this in i os7

in ios6 it is working fine.

**Comment by swabzz** [comment]
Cant open .pkpass with simulator ?

Any update?

**Comment by tschoffelen** [comment]
Please have a look at the console and device logs, the reason it won't open the file should be listed in there somewhere.

**Comment by swabzz** [comment]
Yes it is working now.

It was problen in exporting certeficate from keychain 

Thanks for your help
