### ISSUE TITLE
Possible to save .pkpass File on Server?

### ISSUE THREAD

**Issue by mrweix** [tschoffelen/PHP-PKPass#51]
Is it possible to save the generated .pkpass file directly on the server instead of downloading it?

**Comment by tschoffelen** [comment]
Yes, that's quite simple: if you have a instance `$pass` (see examples/example.php for full usage), simply call `$pass->create(false)` and save the output:

     $pass_content = $pass->create(false); // adding false keeps it from downloading
     if(!$pass_content){
        die('Something went wrong.');
     }

     file_put_contents('mypass.pkpass', $pass_content); // save to a file, first param is filename
