### ISSUE TITLE
iOS 9: Safari cannot download this file

### ISSUE THREAD

**Issue by memento86** [tschoffelen/PHP-PKPass#52]
HI!
The pkpass file doesn't work at iphone devices. When the file is downloaded by Safary, it is showed this error: "Safari cannot download this file". I am testing with simulator of xcode and show the next logs:

Jun 23 17:45:52 iMac assertiond[586]: assertion failed: 15C50 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Jun 23 17:46:01 --- last message repeated 13 times ---
Jun 23 17:46:01 iMac MobileSafari[646]:  SecTrustEvaluate  [leaf SubjectOrganizationalUnit]
Jun 23 17:46:01 iMac MobileSafari[646]: Invalid data error reading pass pass.com.enubes.repsolmas/325225. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.
Jun 23 17:46:01 --- last message repeated 1 time ---
Jun 23 17:46:01 iMac MobileSafari[646]: PassBook Pass download failed: The pass cannot be read because it isn’t valid.

I have generated the p12 file like you say at https://github.com/tschoffelen/PHP-PKPass#requesting-the-pass-certificate.

Finally, I can install the pkpass at Android devices.

I hope that you can help me.

Thank you!

**Comment by tschoffelen** [comment]
Hi! It seems that something is wrong with the certificate embedded in the pass:

    The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.

A few things to try:

- Retry exporting the certificate from your keychain, and make sure you enter the same password you use during the export in the example code.
- Make sure you have downloaded the WWDR certificate, it is readable and in the right place.
- Make sure the team identifier and the pass type identifier in the example code match the values in the developer portal.

**Comment by memento86** [comment]
Hi!
Thanks for your answer. But I have done every step a lot of times and pkpass doesn´t work on iphone device. I don'´t know that try...

**Comment by tschoffelen** [comment]
Did you try emailing the pass to yourself and opening it from the Mail app on your iPhone?

**Comment by memento86** [comment]
It works now :) I have generated the p12 certificate using other mac. You can close the issue.

Thank you!
