### ISSUE TITLE
I'm getting PKPasses of size 0Kb

### ISSUE THREAD

**Issue by prathammehta** [tschoffelen/PHP-PKPass#53]
I've followed all the steps in the readme to get the example.php working. I've added all the certificates correctly as far as I can tell. I'm hosting the whole thing on localhost. Is this a problem? 

When I access it on the iPhone it says file cannot be downloaded and when I click on it on my mac, it says the file cannot be opened. 

Any advice would be great. Thanks!

**Comment by tschoffelen** [comment]
Getting a pass file of a size of 0kb probably means that the Zip compression fails. Please check if you have the [zip extension](http://php.net/manual/en/book.zip.php) installed and it is active on your system.

**Comment by prathammehta** [comment]
Alright. I'll do that. Thanks :)

**Comment by prathammehta** [comment]
![screen shot 2016-06-28 at 2 14 42 pm](https://cloud.githubusercontent.com/assets/3429759/16409361/be50e056-3d3a-11e6-9d26-e99298cc9334.png)
It shows up in the phpinfo(). Do you think it's still this that's causing the issue?

**Comment by tschoffelen** [comment]
Okay, that makes it a little less likely that is the problem. Can you try adding the following two lines at the top of the example code and see if it outputs any errors?

```
ini_set('display_errors',1);
error_reporting(E_ALL);
```

**Comment by prathammehta** [comment]
Just tried it. No difference. No errors. Just spits out the same empty file. :/
Any clues as to what else it could be?
Do I need to run it on a https host for it to work?

**Comment by tschoffelen** [comment]
HTTPS is not necessary for only downloading the pass, only for downloading it on an iDevice. I honestly don't have any other ideas, other than trying to test the ZIPArchive library standalone and looking if it works then. It works on my mac with the default settings, so not sure what's causing this.

**Comment by TheSquidly** [comment]
Hey,
I have had the same problem. 
To solve this you either have to print the variable "$file" from "PKpass.php" at the end of the function "create" or print the return value of that function in the example.php wich is probably the better idea.

**Comment by prathammehta** [comment]
Gonna go try this right away! Thanks :D

**Comment by prathammehta** [comment]
This worked perfectly! Thank you so much! :D

Just added a "echo $file" before the return statement in the create() function.
