### ISSUE TITLE
Empty .pkpass files

### ISSUE THREAD

**Issue by jskidd3** [tschoffelen/PHP-PKPass#54]
Whenever I run examples/example.php all that is exported is an empty .pkpass file. I have spent many hours reading through very carefully and started over several times but cannot get this library to work. Can anyone please shed light on why this is happening?

I have set paths, permissions, ownership etc on all of the required files as well as ensured that all variables (eg team ID, pass ID etc) are set.

**Comment by tschoffelen** [comment]
Try adding the following lines at the top of example.php (after the `<?php`):

```
ini_set('display_errors',1);
error_reporting(E_ALL);
```

And see if it outputs any errors. If it does, post it here, than I might be able to help you with this specific case.

**Comment by jskidd3** [comment]
I tried running the script with root using the command line with `php example.php > example.pkpass` and this produced the pass correctly.

That must mean this is a permission issue, right? Thanks - appreciate your help with this.

**Comment by jskidd3** [comment]
After further investigation, in the `create` method if I dump the file to the server, `file_put_contents('test.pkpass, $file);`, then the pass is valid and correct (33,340 bytes). However, when `create` reaches `echo $file;`, it just downloads an empty pass to the browser.

**Comment by wayneworks** [comment]
Joel,

I had the same problem a month ago with creating a pass. It ended up being something in the class file that was deleting the file too fast. I ended up commenting out the unlink command then my pass started working perfectly.

On Jul 22, 2016, at 8:06 PM, Joel <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried running the script with root using the command line with php example.php > example.pkpass and this produced the pass correctly.

That must mean this is a permission issue, right? Thanks - appreciate your help with this.

**Comment by jskidd3** [comment]
@wayneworks That fixed the problem! Thanks so much :smiley:

**Comment by tschoffelen** [comment]
@jskidd3, would you mind opening a pull request with the changes you made? Might be useful for others as well. Thanks!

**Comment by wayneworks** [comment]
no problem glad that helped.

On Jul 23, 2016, at 6:48 AM, Joel <notifications@github.com<mailto:notifications@github.com>> wrote:


@wayneworks<https://github.com/wayneworks> That fixed the problem! Thanks so much 😃
