### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by sureshborras** [tschoffelen/PHP-PKPass#58]
Hi ,
I integrated this code . it was done successfully.  But I am struck register device to send push notification to device (push notification web service). I am a php developer , I am trying integrate apns and gcm. But I was fail . Please provide any example code of pass push notification. Please Help me.

**Comment by tschoffelen** [comment]
Unfortunately, sending notification is outside the scope of this library. Have a look at this library: https://github.com/jwage/php-apns
