### ISSUE TITLE
Code has generated pass.pkpass with Zero bytes

### ISSUE THREAD

**Issue by agravatfemina** [tschoffelen/PHP-PKPass#60]
Please help me to resolve this.
1. I've Set the path to my Pass Certificate 
2. I've Set password for certificate
3.I've Set the path to my WWDR Intermediate certificate
4.I've set my passTypeIdentifier
5.I've set my teamIdentifier

What is the point of issue? 

![screen shot 2017-02-07 at 11 36 21 am](https://cloud.githubusercontent.com/assets/14847277/22679641/adb16d0c-ed29-11e6-86a9-f82decb71544.png)

**Comment by tschoffelen** [comment]
Have a look at the comments on #54, which contain some suggestions.

**Comment by agravatfemina** [comment]
Yes, iI tired that but that not works for me. ButI got the solution from here: https://github.com/tschoffelen/PHP-PKPass/issues/53 . I've just added "echo $file" before the return statement in the create() function. 

That's work for me!

But is this the correct way to resolve this issue?

**Comment by tschoffelen** [comment]
I've updated the class. Can you test if it resolves your issue?

**Comment by agravatfemina** [comment]
Yes, that works for me! Thank you, buddy 👍  . I've gone through the code , So this would be only change **readfile($paths['pkpass']);** with **echo $file;** . Right ?

**Comment by tschoffelen** [comment]
I also changed some stuff around file names, but that's probably not necessary for it to work correctly.

**Comment by agravatfemina** [comment]
Ok. Right now this is work correctly. Thank you for your prompt reply & support.You saved my day.I am closing this issue
