### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by 045WEB** [tschoffelen/PHP-PKPass#61]
Hi,
safari on iphone with IOS 10.2.1 return me download error.
All certificate and psw are correct.. why?

thanks best regards

**Comment by 045WEB** [comment]
If i try to send the pass.pkpass file through email, Mail on iphone crash when i click on the file.

**Comment by tschoffelen** [comment]
Try connecting your iPhone to your mac and opening the iPhone console in Xcode. It will probably explain to you what's going wrong.

**Comment by 045WEB** [comment]
Hi,
thanks in advanced for your answer.

this is the page i load:

http://www.045web.it/pass1/examples/full_sample/ <http://www.045web.it/pass1/examples/full_sample/>

the console show me a “Failed to load resource: frame load interrupted” when i try to download the pass after submit the form.

This is the pass downloaded via imac


Is strange because un mac Mail is shown correctly as this print screen:




But on iphone return me wrong.

I will gladly give you a donation if you will help me, ‘cause is very important for me to solve the problem!
Thanks, best regads.







Luca Ponso
Web Developer

045WEB snc
Via Del Partigiano, 4
37053 Cerea, Verona
www.045web.it <http://www.045web.it/>

+39 328 2174314
luca@045web.it
linkedin.com/in/lucaponso <http://www.linkedin.com/in/lucaponso>

----------------------------------------------------------------------------------

INFORMATIVA RELATIVA ALLA TUTELA DEI DATI PERSONALI
Ai sensi del D.Lgs. 196/2003 si precisa che le informazioni contenute 
in questo messaggio sono riservate ad uso esclusivo del destinatario.
Qualora il messaggio le fosse pervenuto per errore, La invito ad
eliminarlo senza copiarlo e a non inoltrarlo a terzi,
dandomi gentilmente comunicazione all’indirizzo info@045web.it <mailto:info@045web.it>.
Ringrazio per la cortese collaborazione.

**Comment by tschoffelen** [comment]
Hi, send me a private email (thomas at scholica.com) if you still haven't been able to figure it out, and I can look at it for you in some more detail.
