### ISSUE TITLE
 Cannot read the cerficate

### ISSUE THREAD

**Issue by Cafnio** [tschoffelen/PHP-PKPass#65]
Hi there.

First of all, thanks for the plugin and all the work.

I'm trying to put the example working, so I'm accessing the following url:
http://localhost:8080/examples/example.php

Here's the folder configuration:
https://i.gyazo.com/943a8d0c7326c2046e7063c62b79f260.png

Accessing that url, it returns to me:
Error: Could not read the certificate

Any help?

Thanks

**Comment by tschoffelen** [comment]
Seems like Certificate.p12 is in the same directory as example.php, so the path in line 8 should simply be `Certificate.p12`. If that doesn't work, make sure the script has read permissions for the `Certificate.p12` file.

**Comment by Cafnio** [comment]
Hello!

Thanks for the help.

I'll have to check the permissions anyway :)

I've editted the code to allow it to work with urls (want to load the file from cdn), I got it working, it creates the file but I can't open the pkpass, it says "the pass pass.pkpass" cannot be opened. Is there any way I can debug it to see what i'm doing wrong?

**Comment by tschoffelen** [comment]
Try using the **Console** app on your mac. That should show detailed debugging errors. Most likely, either the JSON string you are passing isn't valid, or doesn't comply with Apple's scheme.

**Comment by Cafnio** [comment]
Well, i'm using the example.php json, I haven't changed anything from there (only url's).

Will try to get an Iphone to see if I can get the debugging working. Thanks
