### ISSUE TITLE
Can't Open pkpass

### ISSUE THREAD

**Issue by cincaw** [tschoffelen/PHP-PKPass#68]
Hi, I've follow all the instruction and already generated the .p12 file, but I still get this following error at my macbook console after I tried to open the .pkpass file on my iPhone. My pass ID and Team ID is right, and I've already generate the .p12 file.

Error Log:
Invalid data error reading card pass.com.test.example/serial_number. The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.

**Comment by tschoffelen** [comment]
This would indicate that the P12 file was generated incorrectly. Sometimes going through that process again makes it magically works – Apple certificates are a complicated matter... 

Also make sure that the password you use to export the certificate is the same you use at the top of the script, if any.

Sorry I can't give any more specific advice!

**Comment by cincaw** [comment]
Thank you so much, finally it's worked as I generated the P12 again.
