### ISSUE TITLE
Failed to load resource: Frame load interrupted on safari.

### ISSUE THREAD

**Issue by kavya145** [tschoffelen/PHP-PKPass#74]
Hi 
When I execute the code I am facing the issue while downloading it says **Failed to load resource: Frame load interrupted**. 

not able to figure out the error here and if i execute the online link of your example "http://pkpass.dev.scholica.com/examples/full_sample/" it works correctly.

please assist me in this.

**Comment by tschoffelen** [comment]
This seems like something to do with the PHP execution on your server. Are you sure the Zip and OpenSSL extensions are installed and active?

**Comment by kavya145** [comment]
i am running on CENTOS with WHM

**Comment by tschoffelen** [comment]
That doesn't really tell me much – those extensions need to be installed separately on some systems.
