### ISSUE TITLE
How to add *.lproj folders and corresponding pass.strings files properly?

### ISSUE THREAD

**Issue by twinpigs** [tschoffelen/PHP-PKPass#75]

**Comment by UnnikrishnanBhargavakurup** [comment]
Hi,

I was also facing an issue of adding localized content to the pass file. I have forked the repo and introduced two functions for adding localized content to the pass archive. 

You can see the pull request here: https://github.com/tschoffelen/PHP-PKPass/pull/78

Pease let me know if it appropriate.

Thanks,
Unnikrishnan B.
