### ISSUE TITLE
Pass Service missing last modified header

### ISSUE THREAD

**Issue by Maarco73** [tschoffelen/PHP-PKPass#76]
Pass Service returned "log":
{"logs":["[2018-01-10 11:59:51 +0100] Web service error for xxxxx  (xxxxx: Server returned the pass data for serial number 'xxxx' but did not provide a 'last-modified' header."]}

I fixed this by adding:
`header("Last-Modified: ".gmdate("D, d M Y H:i:s", time())." GMT");`
after line 318 (where all te header() stuff is)

**Comment by tschoffelen** [comment]
Thanks, I'll implement this into the code!
