### ISSUE TITLE
No support for .p8 files

### ISSUE THREAD

**Issue by oskar-kupski-valueadd** [tschoffelen/PHP-PKPass#77]
Hi,
I can't really generate .p12 file and password to it. I can just add a key and download .p8 file. Am I doing something wrong? I read that Apple has moved from .p12 to .p8 files.

**Comment by tschoffelen** [comment]
They moved to P8 for push notifications, but I think nothing has changed yet with Pass IDs. Did you follow the instructions in the readme?

**Comment by oskar-kupski-valueadd** [comment]
Hi @tschoffelen, thanks for answer I managed to create .p12 file but now I get an error in example.php file that says: "Error: Invalid certificate file. Make sure you have a P12 certificate that also contains a private key, and you have specified the correct password!". I tried 3 times with creating new certificate and double-checked password, passTypeId  and teamId, but still an error appears

**Comment by oskar-kupski-valueadd** [comment]
It resolved the issue, thanks
