### ISSUE TITLE
How to add personalization files ?

### ISSUE THREAD

**Issue by GCalmels** [tschoffelen/php-pkpass#79]
Hey, 
Thank you for this library !

I would like to know if it is possible to add personalization files like `personalization.json` for [Reward Enrollment](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/PassPersonalization.html#//apple_ref/doc/uid/TP40012195-CH12-SW2)? 

I tried `addFile` without any success ! 

Thanks
Gabriel

**Comment by tschoffelen** [comment]
`addFile` should work for that. Can you share some of your code?

**Comment by GCalmels** [comment]
Ok, I will try again :) 
My code is : 
```php
$personalisationFile = self::PASS_DIRECTORY . 'personalization.json';
$pass->addFile($personalisationFile, 'personalization.json');`

**Comment by tschoffelen** [comment]
And do you get an error from the script itself, or does it just not work on the Wallet-side? 

Because I think you might also need to include the files `personalizationLogo@1x.png`, `personalizationLogo@2x.png` and `personalizationLogo@3x.png` to make rewards enrollment work. From the docs:

> Use a 150 x 40 point png file. This logo is displayed at the top of the signup form.

**Comment by GCalmels** [comment]
It just not work on the Wallet side... it seems to be an invalid pass ! But `addFile` add personalization.json in the manifest ! 

My bad, I have an error in Console : `Passes with an NFC dictionary or a Personalization JSON file must be signed with an enhanced Passbook certificate.`

Thanks for your responsiveness 👍
