### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by pingu1** [tschoffelen/php-pkpass#80]
### Expected Behavior

I would like to use the `$pkpass->addRemoteFile($url, $name)

### Actual Behavior

This function is not part of `1.1.0`

Would it be possible to check the stability of the project, and generate a new version for packagist? I could also fork the project but this function is like 9months old, it would be great to have it available to everyone.

Thanks

**Comment by tschoffelen** [comment]
Apologies, I seem to indeed have forgotten to update the package. Just released version [1.2.0](https://packagist.org/packages/pkpass/pkpass#v1.2.0).
