### ISSUE TITLE
it doesn't working in ios

### ISSUE THREAD

**Issue by iamabhyas** [tschoffelen/php-pkpass#84]
### Expected Behavior
.pkpass file working in android good but in ios does not work.

**Comment by tschoffelen** [comment]
Hi,

That usually means that the certificate that you're using to sign your pass isn't valid. Android apps don't check if the pass is valid and just display it, while iOS only displays the pass if it is signed with a valid signature.

1. Signing your passes for use in iOS Wallet requires an active, paid [Apple Developer account](https://developer.apple.com/programs/).
2. Make sure to check if you completed [all the steps](https://github.com/tschoffelen/php-pkpass#requesting-the-pass-certificate) to request, download and add the certificate.
3. Make sure you [have specified](https://github.com/tschoffelen/php-pkpass#getting-the-examplephp-sample-to-work) the correct `passTypeIdentifier`, `teamIdentifier` and certificate path and password in your code.
4. If none of these things seem to help, connect your iPhone to a Mac and check [the Console app](https://github.com/tschoffelen/php-pkpass#debugging-passes) for error messages.

The library has been successfully verified to work with all iOS versions from iOS 6 and up, as long as you sign it with a valid certificate and team identifier.

**Comment by iamabhyas** [comment]
Thank you so much Thomas Schoffelen.
