### ISSUE TITLE
WebServiceURL 

### ISSUE THREAD

**Issue by Shafiullahbug** [tschoffelen/php-pkpass#85]
I have a question is there an example code for updating of pass. As soon as I try to insert a weserviceurl into the pass the pass is not recognised by the wallet app.

**Comment by tschoffelen** [comment]
We don’t have an example on how to do that right now.

I would suggest the following to troubleshoot this:

- Make sure either your webserviceUrl is HTTPS, or temporarily enable HTTP URLs in the Developer menu of the Settings app on your iPhone.
- Connect your iPhone to a Mac and use the Console app to look for errors, as decribed in the Readme of this repo.

**Comment by tschoffelen** [comment]
Any luck figuring this out @Shafiullahbug?

**Comment by Shafiullahbug** [comment]
Hey @tschoffelen Thanks for your reply ....... Not yet but I will start working on it from Monday and will update you once done ....... I should be able to do it have a lot on my plate so havent been able to work on this .....

**Comment by zloadmin** [comment]
<img width="956" alt="screenshot at jan 18 7-03-43 pm" src="https://user-images.githubusercontent.com/6871864/51386077-cb62dc00-1b53-11e9-81a3-c6c770bab67c.png">
You have to add:

```
"webServiceURL" => "https://your_domian", // only https
"authenticationToken" => "your_token",
```

**Comment by RaiserWeb** [comment]
Hi @zloadmin , I am adding webServiceURL and authenticationToken, and the pass gets created and successfully added to iOS wallet on iPhone.

But my webServiceURL is not getting hit when the pass is added on the iPhone - I've set up the URL to log request data, so I can inspect what apple sends. It is https, of form domain.com/passbook-update

I am using the cert to generate the pass as per the readme of this repo. Not sure what I am doing wrong, any ideas would be welcome. I've looked at the console log of the iPhone but no errors.

**Comment by tschoffelen** [comment]
If anyone wants to open a PR to contribute any of this info to the README, that would be super helpful.

Closing this issue right now, since the actual server implementation of push isn't really within the scope of this repo right now.
