### ISSUE TITLE
PKPassKitErrorDomain Error

### ISSUE THREAD

**Issue by exaflare** [tschoffelen/php-pkpass#86]
### Actual Behavior
Hi, I'm getting this error : 
fault	11:08:47.017293 +0400	MobileSafari	PassBook Pass download failed: Error Domain=PKPassKitErrorDomain Code=1 "(null)"

I'm already followed each step that you provided

**Comment by pirlango** [comment]
I am having exactly the same error when I try to open the pkpass file in my Mac.

If it helps I have also tried to open it unzipping the file with command line (it works for files generated directly with signpass) and the error is

unzip pass.pkpass 
Archive:  pass.pkpass
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of pass.pkpass or
        pass.pkpass.zip, and cannot find pass.pkpass.ZIP, period.
