### ISSUE TITLE
Files name error 

### ISSUE THREAD

**Issue by zloadmin** [tschoffelen/php-pkpass#87]
I got same error - https://stackoverflow.com/questions/18440961/wrong-app-icon-on-push-notification-badge-iphone

When i have a few passes on one device and i send notification to one pass - i see wrong icon!

**Comment by twinpigs** [comment]
Try to use different Type IDs for each one.

**Comment by zloadmin** [comment]
> Try to use different Type IDs for each one.

Thanks!
