### ISSUE TITLE
no pass generated

### ISSUE THREAD

**Issue by livedevel** [tschoffelen/php-pkpass#98]
using your scripts i get a pkpass file.
I cant open it on iphone.
When i try to debug it in xcode simulator no error is thrown.

is the script still working? Becuse on https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1
there is PKCS #7 mentioned and not 12

thanx for help

**Comment by tschoffelen** [comment]
Hi there,

Yep, I'm certain that the library still works. It's used in a lot of production environments.

Have you tried the debugging instructions from the README?

https://github.com/tschoffelen/php-pkpass#debugging-passes

**Comment by livedevel** [comment]
Hi :-),

i have access to the console. i tried the iphone, and the simulator, but i get no message inside the console.
it seems like the file is recognized by the extention .pkpass. but wenn i try to use it, nothing happens.
not even a error message.
:-/
